### ISSUE TITLE
Is this compatible with 7.6.x?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [7elix/formhandler#6]
I'm trying to use it but I'm actually getting

```
Could not analyse class: "Tx\Formhandler\Controller\LogController" maybe not loaded or no autoloader?
```

on the backend, when I click on the "Formhandler" tab on the left.

Thank you in advance,
Julian

**Comment by 7elix** [comment]
This is only a copy of https://svn.typo3.org/TYPO3v4/Extensions/formhandler/branches/typo37-compat/.
Please head over to the official repository.

**Comment by julianxhokaxhiu** [comment]
Yep thank you anyway.

I found that there's a branch compatible with 7.6 already in the official Forge repository.

**Comment by Prizzler** [comment]
hi julianxhokaxhiu,
can you give me the link to the official Forge repository.
thx

**Comment by julianxhokaxhiu** [comment]
@Prizzler: https://forge.typo3.org/projects/extension-formhandler/repository/show/branches/typo37-compat

To clone it you should do something like this ( if I don't remember wrong, I don't remember it atm )
```
svn co https://svn.typo3.org/TYPO3v4/Extensions/formhandler/branches/typo37-compat formhandler
```

**Comment by Prizzler** [comment]
thx for the fast reply!
